train:
  id: csgo
  size: [150, 280]
num_actions: 51
path_data_low_res: C:\Users\Administrator\Downloads\out_dir\low_res # TO DEFINE
path_data_full_res: C:\Users\Administrator\Downloads\out_dir\full_res # TO DEFINE
keymap: csgo
